# Generated by Django 2.2 on 2019-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191211_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]
